// This file provides the Playwright configuration for running test specs generated by the crawler.
import { defineConfig, devices } from 'playwright/test';

export default defineConfig({
  testDir: './output/playwright',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: 'list',
  use: {
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
