// This file defines the root layout for the Sparkier regression dashboard UI.
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Sparkier Regression Dashboard',
  description: 'Visualise automated user story coverage and Playwright outlines generated by the Sparkier web auditor.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="min-h-screen bg-slate-50 font-sans">{children}</body>
    </html>
  );
}
